name: smart_city_app
description: "A new Flutter project."
publish_to: 'none' # Bu paketi pub.dev'e göndermeyelim.

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.2.1
  get: ^4.6.6
  dio: ^5.7.0
  intl: ^0.19.0
  url_launcher: ^6.0.9
  html: ^0.15.5
  convert: ^3.1.2
  flutter_datetime_picker_plus: ^2.2.0
  flutter_launcher_icons: ^0.14.1
  font_awesome_flutter: ^10.8.0
  google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4  # Dart 3.6.x + Flutter test_api 0.7.3 ile uyumlu

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon3.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
