// Mocks generated by Mockito 5.4.5 from annotations
// in smart_city_app/test/unit_tests/pazar_yeri_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i10;

import 'package:get/get.dart' as _i2;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i9;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:smart_city_app/controllers/map_controllers/map_controller.dart'
    as _i7;
import 'package:smart_city_app/core/api/pazarYeri/pazar_yeri_api_model.dart'
    as _i6;
import 'package:smart_city_app/core/api/pazarYeri/pazar_yeri_api_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRxSet_0<E> extends _i1.SmartFake implements _i2.RxSet<E> {
  _FakeRxSet_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRx_1<T> extends _i1.SmartFake implements _i2.Rx<T> {
  _FakeRx_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_2 extends _i1.SmartFake implements _i2.RxBool {
  _FakeRxBool_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_3<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PazarYeriApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPazarYeriApiService extends _i1.Mock
    implements _i3.PazarYeriApiService {
  MockPazarYeriApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get pazarYeriApiUrl =>
      (super.noSuchMethod(
            Invocation.getter(#pazarYeriApiUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#pazarYeriApiUrl),
            ),
          )
          as String);

  @override
  _i5.Future<List<_i6.Onemliyer>> getPazarYerleri() =>
      (super.noSuchMethod(
            Invocation.method(#getPazarYerleri, []),
            returnValue: _i5.Future<List<_i6.Onemliyer>>.value(
              <_i6.Onemliyer>[],
            ),
          )
          as _i5.Future<List<_i6.Onemliyer>>);
}

/// A class which mocks [MapController].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapController extends _i1.Mock implements _i7.MapController {
  MockMapController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RxSet<_i8.Marker> get markers =>
      (super.noSuchMethod(
            Invocation.getter(#markers),
            returnValue: _FakeRxSet_0<_i8.Marker>(
              this,
              Invocation.getter(#markers),
            ),
          )
          as _i2.RxSet<_i8.Marker>);

  @override
  _i2.Rx<_i8.LatLng> get initialPosition =>
      (super.noSuchMethod(
            Invocation.getter(#initialPosition),
            returnValue: _FakeRx_1<_i8.LatLng>(
              this,
              Invocation.getter(#initialPosition),
            ),
          )
          as _i2.Rx<_i8.LatLng>);

  @override
  _i2.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_2(this, Invocation.getter(#isLoading)),
          )
          as _i2.RxBool);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_3<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void addMarkers({
    required List<dynamic>? locations,
    required double Function(dynamic)? getLatitude,
    required double Function(dynamic)? getLongitude,
    required String Function(dynamic)? getTitle,
    required String Function(dynamic)? getSnippet,
  }) => super.noSuchMethod(
    Invocation.method(#addMarkers, [], {
      #locations: locations,
      #getLatitude: getLatitude,
      #getLongitude: getLongitude,
      #getTitle: getTitle,
      #getSnippet: getSnippet,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Disposer addListener(_i9.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i9.Disposer);

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i10.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Disposer addListenerId(Object? key, _i9.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i9.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
